### ISSUE TITLE
 list optional action fall through ETYPECASE expression

### ISSUE THREAD

**Issue by mfkhr** [fare/command-line-arguments#5]
command-line-action() was modified to accept cons instead of function,
, on the other hand, make-option-action() generates lambda function for list as before.
lambda function need to be wrapped in cons?
["with" option fail when use the pgloader cli #1055](https://github.com/dimitri/pgloader/issues/1055)

**Comment by fare** [comment]
Oops. Can you send a PR? I admit I'm not currently using this library much, having migrated my development away from CL to Gerbil Scheme.

**Comment by fare** [comment]
Can you confirm that the issue is solved and then close?
